# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0004_auto_20180424_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access',
            new_name='position',
        ),
    ]
