# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_auto_20180424_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='members',
            field=models.ManyToManyField(related_name='my_courts', to='ports.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to='ports.User'),
        ),
    ]
