# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0007_auto_20180424_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagged_photo',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagged_photo',
            field=models.ManyToManyField(related_name='tags', to='ports.Photo'),
        ),
    ]
