# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0009_auto_20180425_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='my_groups', to='ports.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='court',
            name='members',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
    ]
