# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0010_auto_20180425_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likers',
            field=models.ManyToManyField(related_name='liked_photos', to='ports.User'),
        ),
    ]
