# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0011_auto_20180425_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='user_level',
        ),
    ]
