# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0014_auto_20180426_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='ports.User'),
        ),
    ]
