# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0016_auto_20180426_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
