# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0019_user_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
