# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 08:40
from __future__ import unicode_literals

import apps.ports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0020_remove_user_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', null=True, upload_to=apps.ports.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
