# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 08:58
from __future__ import unicode_literals

import apps.ports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0021_auto_20180427_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/default.jpg', upload_to=apps.ports.models.user_directory_path_profile),
        ),
    ]
