# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 17:31
from __future__ import unicode_literals

import apps.ports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0022_auto_20180427_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=apps.ports.models.user_directory_path_profile),
        ),
    ]
