# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0025_auto_20180711_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 20, 24, 39, 518000)),
            preserve_default=False,
        ),
    ]
