# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0026_plan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='client',
            new_name='host',
        ),
    ]
