# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0027_auto_20180712_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='ports.User'),
            preserve_default=False,
        ),
    ]
