# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0028_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='address',
            field=models.CharField(default='121 Bodega Court', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='121 Bodega Court', max_length=255),
            preserve_default=False,
        ),
    ]
