# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0030_auto_20180730_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messengers',
            field=models.ManyToManyField(null=True, related_name='my_chatrooms', to='ports.User'),
        ),
    ]
