# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 18:03
from __future__ import unicode_literals

import apps.ports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0036_auto_20180802_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=apps.ports.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=apps.ports.models.user_directory_path_profile),
        ),
    ]
